// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Sensor readings
//
//	Return sensor readings from database
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/network.golang.demoapi-measurement.v1+json
//
//	Produces:
//	  - application/network.golang.demoapi-list.v1+json
//
// swagger:meta
package restapi
