consumes:
    - application/network.golang.demoapi-measurement.v1+json
info:
    description: Return sensor readings from database
    title: Sensor readings
    version: 1.0.0
paths: {}
produces:
    - application/network.golang.demoapi-list.v1+json
schemes:
    - http
swagger: "2.0"
